### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by aicastell** [bg111/asterisk-chan-dongle#230]
Hello.

In the initialization of at_responses_list structure (at_response.c file) you can find this code:
    ...
    { RES_CMGS,"+CMGS",DEF_STR("+CMGS:") },
    { RES_CMGS,"+CPMS",DEF_STR("+CPMS:") },
    ...

But I think this is wrong, and it should be:

    ...
    { RES_CMGS,"+CMGS",DEF_STR("+CMGS:") },
    { RES_CPMS,"+CPMS",DEF_STR("+CPMS:") },
    ...

Hope this helps!

**Comment by hselasky** [comment]
Hi,

Did you check that the new modified code compiles?

--HPS

**Comment by aicastell** [comment]
Yes, of course!

**Comment by bg111** [comment]
Fixed in 44
