### ISSUE TITLE
Device requirements

### ISSUE THREAD

**Issue by hryamzik** [bg111/asterisk-chan-dongle#245]
Is there a list of features or commands that should be supported by device to work with chan_dongle? I did see the list of supported modems but don't get why others are not supported and if there's any chance to get landline modems work with this software.

**Comment by VGBLTSK** [comment]
Chan_dongle is compatible with Huawei modems that are 11.XX firmware based. You may refer to the list of AT commands supported by your dongle by issuing: 
AT ^ CMDL : get a list of all the commands

What is 'landline modem'?

**Comment by hryamzik** [comment]
Landline modem is a voice modem for wired connections. I'm aware that asterisk doesn't seem to support any of them and require special FXO devices but after reading these topics for a day didn't find any reason for that.

**Comment by VGBLTSK** [comment]
Chan_dongle as I wrote before is for Huawei only devices. The list of supported modems with some caveats is available.

**Comment by hryamzik** [comment]
The question is what makes Huawei modems special, is it a list of supported AT commands or anything else?

**Comment by VGBLTSK** [comment]
I am not a chan_dongle developer and can't explain if there is any special interface handlers or device initiating scripts. However, I have been using this channel driver for quite a bit and can tell you for sure that this guy is really sensitive to the list of certain AT commands. Different Huawei firmware revisions like 11.XX and 21.XX use slightly different set of commands. This ends up with some unexpected modem disconnections. Hence, the answer is likely YES.

**Comment by hryamzik** [comment]
Got it, thanks!

**Comment by VGBLTSK** [comment]
You are most welcome.

**Comment by Izaq786** [comment]
Sir I have [

[L206(C,D)_AT_DOCUMENT_V1.07 (1).pdf](https://github.com/user-attachments/files/20852785/L206.C.D._AT_DOCUMENT_V1.07.1.pdf)

](url)

Will it work in chan dongle 
Coz frm last 2 month I am trying to connect but 
I am getting time out no response at AT command 
Through minicom and python I am getting AT command can also call ATD but ATE0 is not working in minicom plz let me know in Asterisk chan dongle debug i did open tty is successful and lock file is also successful but do monitor phone is timeout 
I want to know will this modem will work or not so I will work on it or els I will stop
