### ISSUE TITLE
How to place call files

### ISSUE THREAD

**Issue by gkov9** [bg111/asterisk-chan-dongle#248]
Hello,

I would like to place calls with asterisk call files, using a 3G USB stick. Let's say I have a custom trunk named VFUSB. What shall I put in the call file to use chan_dongle? 

In the asterisk wiki it says: "Channel: <channel> - The channel to use for the new call, in the form technology/resource as in the Dial application. This value is required."

So what is the technology/resource value I should put to use a 3G USB stick?

Thanks,

**Comment by VGBLTSK** [comment]
Did you check this page?
http://www.raspberry-asterisk.org/documentation/gsm-voip-gateway-with-chan_dongle/

**Comment by gkov9** [comment]
Yes, I did, unfortunatelly there is nothing about call files in it.

**Comment by VGBLTSK** [comment]
What do you mean by 'call files'?

**Comment by gkov9** [comment]
I mean this: https://wiki.asterisk.org/wiki/display/AST/Asterisk+Call+Files . It is a very usefull feature of asterisk.

**Comment by gkov9** [comment]
I solved the problem. For those interested in the solution, here is what needs to be set:

Dongle/dongle0/<the number to be dialed>

Of course, dongle0 could be dongle1 if there are more than one dongles connected to the Rpi.

And don't forget to set an appropriate dial plan on the trunk (in my case it was just a ".").
