### ISSUE TITLE
SIM800

### ISSUE THREAD

**Issue by leobaccili** [bg111/asterisk-chan-dongle#252]
Hello guys
If is a stupid question, please forgive me, but It's possible to use raspberry + sim800 module with this library?

**Comment by streamel** [comment]
google http://www.raspberry-asterisk.org/documentation/gsm-voip-gateway-with-chan_dongle/

**Comment by s1lviu** [comment]
> Hello guys
> If is a stupid question, please forgive me, but It's possible to use raspberry + sim800 module with this library?

Hi, @leobaccili 
Do you managed to get that working?
