### ISSUE TITLE
Asterisk does not hear dtmf sounds

### ISSUE THREAD

**Issue by Varjasiteodor** [bg111/asterisk-chan-dongle#284]
When I call asterisk from the softphone, it hears dtmf sounds, but when I call from PSTN, it doesn't. This is the output of dongle.conf:
[general]
interval=10000000
jbenable=no

[defaults]
context=from-trunk
group=0
rxgain=0
txgain=0
autodeletesms=no
resetdongle=yes
u2diag=-1
usecallingpres=yes
callingpres=allowed_passed_screen
disablesms=yes
language=en
smsaspdu=yes
mindtmfgap=45
mindtmfduration=10
mindtmfinterval=100
callwaiting=auto
disable=no
initstate=start
exten=+36209238100
dtmf=relax

[Dongle1]
audio=/dev/ttyUSB1
data=/dev/tnt1

**Comment by Varjasiteodor** [comment]
I solved the problem with the asterisk CLI with these AT commands:
``dongle cmd Dongle1 AT^SYSCFG=13,0,3FFFFFFF,0,3

- [ ]

**Comment by rohitg76** [comment]
These are the three parameters that you may want to pay attention to, especially mindtmfduration, which could vary by operator or country. To get the right mindtmfduration, set it to zero, then trace the actual and set it to that or can be left to zero too (I don’t know the side effects of leaving it to zero though).
 
mindtmfgap=45                   ; minimal interval from end of previews DTMF from beginning of next in ms (default 45 ms)
mindtmfduration=50              ; minimal DTMF tone duration in ms (for DTMF in India, reduced to 50) (default 80 ms)
mindtmfinterval=200             ; minimal interval between ends of DTMF of same digits in ms (default 200ms)
 
 
From: Varjasiteodor ***@***.***> 
Sent: Thursday, May 5, 2022 3:40 PM
To: bg111/asterisk-chan-dongle ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bg111/asterisk-chan-dongle] Asterisk does not hear dtmf sounds (Issue #284)
 
When I call asterisk from the softphone, it hears dtmf sounds, but when I call from PSTN, it doesn't. This is the output of dongle.conf:
[general]
interval=10000000
jbenable=no
[defaults]
context=from-trunk
group=0
rxgain=0
txgain=0
autodeletesms=no
resetdongle=yes
u2diag=-1
usecallingpres=yes
callingpres=allowed_passed_screen
disablesms=yes
language=en
smsaspdu=yes
mindtmfgap=45
mindtmfduration=10
mindtmfinterval=100
callwaiting=auto
disable=no
initstate=start
exten=+36209238100
dtmf=relax
[Dongle1]
audio=/dev/ttyUSB1
data=/dev/tnt1
