### ISSUE TITLE
Dongle failed to respond to AT command sometimes in time short time interval

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bg111/asterisk-chan-dongle#97]
```
Dongle is working fine but sometimes it automatically shows message that 
failed to respond AT while waiting ok.... something like this
and dongle reloads automatically and works fine.
but during this time if any call comes, call fail because reload or dongle 
unavailable during reload.

Kindly tell me if dongle does not have any problem ie. i can make and receive 
calls, then why it reloads after a time interval showing the mentioned error?

I am using centos 6.3.
and device Huawei 1 x E173, 2 x E1731, 1 x E180 (total 4 dongle)
```

Original issue reported on code.google.com by `o...@w3host.in` on 22 Oct 2012 at 8:23

**Comment by rfrht** [comment]
I think that I have found what's going on this case.

It seems that the command response parsing is skewed.

See [this pastebin](http://pastebin.com/ED852ear) post. Notice line 54, where it sends the `AT+CGMR`.
It actually parses the __previous__ step result as the firmware version (line 46, `huawei`).

And now, the next command in the stack is the `AT+CMEE=0`, in line 66. The `at_read` program is still reading the firmware from the previous step, and spits the error `Ignoring unknown result: '21.157.31.00.850'` in line 73.

---
The very same is also true for outgoing calls. See the [log snippet](http://pastebin.com/m0azspiV):

Check line 203, where a `AT` is sent. We get this `AT` return in line 209. And then, in line 212 it barfs with `Ignoring unknown result: 'AT` and finally, failing miserably in line 213 `timedout while waiting 'OK' in response to 'AT'`.

---

I think that the solution would  involve a proper serialization of the send/receive/parse AT queue.

**Comment by MoHegazy** [comment]
> I think that I have found what's going on this case.
> 
> It seems that the command response parsing is skewed.
> 
> See [this pastebin](http://pastebin.com/ED852ear) post. Notice line 54, where it sends the `AT+CGMR`.
> It actually parses the **previous** step result as the firmware version (line 46, `huawei`).
> 
> And now, the next command in the stack is the `AT+CMEE=0`, in line 66. The `at_read` program is still reading the firmware from the previous step, and spits the error `Ignoring unknown result: '21.157.31.00.850'` in line 73.
> 
> I think that the solution would involve a proper serialization of the send/receive/parse AT queue.

iam sorry for bringing this up 
but could you tell me what is the solution because i have the same exact problem 
with my dongle E173
thank you

**Comment by rfrht** [comment]
Hi @MoHegazy 

Sorry about that, but I never worked a solution for this issue - it was beyond my coding abilities :-}

I have a fork that I worked a few issues back in the day (2015), but this issue was not the case.

**Comment by MoHegazy** [comment]
> Hi @MoHegazy
> 
> Sorry about that, but I never worked a solution for this issue - it was beyond my coding abilities :-}
> 
> I have a fork that I worked a few issues back in the day (2015), but this issue was not the case.

thank you for your reply 
so changing the dongle would be the solution for this issue 
right?

**Comment by rfrht** [comment]
I don't know man, really :-{

Good luck!!!

**Comment by MoHegazy** [comment]
> I don't know man, really :-{
> 
> Good luck!!!

okay thank you for your help
